import type { ApartmentOffering } from "./types";

export const sampleApartments: ApartmentOffering[] = [
  {
    apartmentId: "demo-hanam-river-1",
    apartmentName: "하남 리버포레 데모단지",
    region: "경기도",
    district: "하남시",
    housingType: "public_sale",
    recruitmentStatus: "open",
    announcementDate: "2026-05-01",
    applicationStartDate: "2026-05-20",
    applicationEndDate: "2026-05-24",
    availableSupplyTypes: ["newlywed_special", "first_life_special", "multi_child_special", "general_supply"],
    ruleVersion: "demo-2026.05-v1",
    sourceNote: "실제 단지가 아닌 데모용 샘플 데이터입니다.",
    disclaimer: "모든 단지 정보는 데모용이며 실제 모집 정보가 아닙니다.",
  },
  {
    apartmentId: "demo-seongnam-tech-1",
    apartmentName: "성남 센트럴파크 데모타운",
    region: "경기도",
    district: "성남시",
    housingType: "private_sale",
    recruitmentStatus: "upcoming",
    announcementDate: "2026-06-03",
    applicationStartDate: "2026-06-18",
    applicationEndDate: "2026-06-22",
    availableSupplyTypes: ["first_life_special", "elderly_parent_special", "general_supply"],
    ruleVersion: "demo-2026.05-v1",
    sourceNote: "실제 단지가 아닌 데모용 샘플 데이터입니다.",
    disclaimer: "모든 단지 정보는 데모용이며 실제 모집 정보가 아닙니다.",
  },
  {
    apartmentId: "demo-gangdong-green-1",
    apartmentName: "강동 그린웨이 데모레지던스",
    region: "서울특별시",
    district: "강동구",
    housingType: "newlywed_hope_town",
    recruitmentStatus: "open",
    announcementDate: "2026-04-28",
    applicationStartDate: "2026-05-12",
    applicationEndDate: "2026-05-16",
    availableSupplyTypes: ["newlywed_special", "institution_recommendation", "general_supply"],
    ruleVersion: "demo-2026.05-v1",
    sourceNote: "실제 단지가 아닌 데모용 샘플 데이터입니다.",
    disclaimer: "모든 단지 정보는 데모용이며 실제 모집 정보가 아닙니다.",
  },
];
